opt_in_rules:
  - empty_count
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - number_separator
  - operator_usage_whitespace
  - toggle_bool
  - empty_string
  - fallthrough
  - convenience_type
  - legacy_random
  - multiline_function_chains
  - multiline_parameters
  - pattern_matching_keywords
  - private_outlet
  - private_action
  - redundant_type_annotation
  - sorted_first_last
  - strict_fileprivate
  - syntactic_sugar
  - modifier_order
  - yoda_condition


disabled_rules:
- multiple_closures_with_trailing_closure
- trailing_comma
- type_name


# paths to include during linting. `--path` is ignored if present.
included:
- Sources
- Tests


# paths to ignore during linting. Takes precedence over `included`.
excluded:


reporter: "xcode"



####
# Individual Rule Configuration (See: https://realm.github.io/SwiftLint/rule-directory.html)
####

vertical_whitespace:
  max_empty_lines: 3

function_parameter_count:
  warning: 5
  error: 7

function_body_length:
  warning: 50
  error: 100

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  warning: 130
  error: 200

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700

large_tuple:
  warning: 4
  error: 6

identifier_name:
  excluded:
    - id
    - up
  validates_start_with_lowercase: false
  max_length: 50

nesting:
  type_level:
    warning: 4

number_separator:
  minimum_length: 5

generic_type_name:
  max_length: 30
